package render

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
)

// Marker is written into every render output directory. WriteTree replaces a
// non-empty directory only if it carries the marker, so a mistyped --out can never
// wipe unrelated data.
const Marker = ".idp-rendered"

// WriteTree replaces dir with files. dir must not exist, be empty, or hold a
// previous render (it contains Marker).
func WriteTree(dir string, files map[string][]byte) error {
	entries, err := os.ReadDir(dir)
	switch {
	case errors.Is(err, fs.ErrNotExist):
	case err != nil:
		return err
	case len(entries) > 0:
		if _, err := os.Stat(filepath.Join(dir, Marker)); err != nil {
			return fmt.Errorf("%s is not empty and is not a previous render (no %s); refusing to replace it", dir, Marker)
		}
		if err := os.RemoveAll(dir); err != nil {
			return err
		}
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	for p, data := range files {
		target := filepath.Join(dir, filepath.FromSlash(p))
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(target, data, 0o644); err != nil {
			return err
		}
	}
	return os.WriteFile(filepath.Join(dir, Marker), []byte("Generated by idp render. This directory is replaced on every render.\n"), 0o644)
}
